MONGO_URL = "mongodb://localhost:27017/"
MONGO_DATABASE = "movie_quiz"
MONGO_USERS_COLLECTION = "users"
MONGO_FILMS_COLLECTION = "films"
MONGO_ACTORS_COLLECTION = "actors"
MONGO_STATISTIC_COLLECTION = "statistic"

TOP_COUNT = 10
CROP_IMAGE_SIZE = 200

VERSION = "2023-10-29-13-00"

RUSSIA_PRODUCTION = "russia"
FOREIGN_PRODUCTION = "foreign"
PRODUCTIONS = [RUSSIA_PRODUCTION, FOREIGN_PRODUCTION]

PRODUCTION_TO_RUS = {
    RUSSIA_PRODUCTION: "российское",
    FOREIGN_PRODUCTION: "зарубежное"
}

QUESTION_MOVIE_BY_BANNER = "banner"
QUESTION_MOVIE_BY_SLOGAN = "slogan"
QUESTION_MOVIE_BY_DESCRIPTION = "description"
QUESTION_MOVIE_BY_SHORT_DESCRIPTION = "short-description"
QUESTION_MOVIE_BY_FACTS = "facts"
QUESTION_MOVIE_BY_AUDIO = "audios"
QUESTION_MOVIE_BY_ACTORS = "actors"
QUESTION_YEAR_BY_MOVIE = "year"

QUESTIONS = [
    QUESTION_MOVIE_BY_BANNER, QUESTION_MOVIE_BY_SLOGAN, QUESTION_MOVIE_BY_DESCRIPTION, QUESTION_MOVIE_BY_SHORT_DESCRIPTION,
    QUESTION_MOVIE_BY_FACTS, QUESTION_MOVIE_BY_AUDIO, QUESTION_MOVIE_BY_ACTORS, QUESTION_YEAR_BY_MOVIE
]

QUESTION_TO_RUS = {
    QUESTION_MOVIE_BY_BANNER: "название по баннеру",
    QUESTION_MOVIE_BY_SLOGAN: "название по слогану",
    QUESTION_MOVIE_BY_DESCRIPTION: "название по описанию",
    QUESTION_MOVIE_BY_SHORT_DESCRIPTION: "название по короткому описанию",
    QUESTION_MOVIE_BY_FACTS: "название по фактам",
    QUESTION_MOVIE_BY_AUDIO: "название по аудио",
    QUESTION_MOVIE_BY_ACTORS: "название по актёрам",
    QUESTION_YEAR_BY_MOVIE: "год по названию, баннеру и описанию"
}

QUESTION_YEARS = [1980, 1990, 2000, 2010, 2015, 2020]


FILM_TYPE = "movie"
CARTOON_TYPE = "cartoon"
SERIES_TYPE = "tv-series"
ANIMATED_SERIES_TYPE = "animated-series"
ANIME_TYPE = "anime"

MOVIE_TYPES = [FILM_TYPE, CARTOON_TYPE, SERIES_TYPE, ANIMATED_SERIES_TYPE, ANIME_TYPE]

MOVIE_TYPE_TO_RUS = {
    FILM_TYPE: "фильм",
    CARTOON_TYPE: "мультфильм",
    SERIES_TYPE: "сериал",
    ANIMATED_SERIES_TYPE: "анимационный сериал",
    ANIME_TYPE: "аниме"
}

LIST_TOP250_FILMS = "top250"
LIST_TOP500_FILMS = "top500"
LIST_TOP250_SERIES = "series-top250"

TOP_LISTS = [LIST_TOP250_FILMS, LIST_TOP500_FILMS, LIST_TOP250_SERIES]

TOP_LIST_TO_RUS = {
    LIST_TOP250_FILMS: "250 лучших фильмов",
    LIST_TOP500_FILMS: "500 лучших фильмов",
    LIST_TOP250_SERIES: "250 лучших сериалов"
}
