MONGO_URL = "mongodb://localhost:27017/"
MONGO_DATABASE = "movie_quiz"
MONGO_USERS_DATABASE = "quiz"
MONGO_USERS_COLLECTION = "users"
MONGO_SETTINGS_COLLECTION = "settings"
MONGO_FILMS_COLLECTION = "films"
MONGO_ACTORS_COLLECTION = "actors"
MONGO_STATISTIC_COLLECTION = "statistic"
MONGO_QUESTION_COLLECTION = "questions"

TOP_COUNT = 10
CROP_IMAGE_SIZE = 200
QUESTION_STATISTICS_LIMIT = 250
REPEAT_PROBABILITY = 0.02
LEADERBOARD_QUESTIONS_COUNT = 100

VERSION = "2023-11-01-22-00"

RUSSIA_PRODUCTION = "russia"
FOREIGN_PRODUCTION = "foreign"
KOREAN_PRODUCTION = "korean"
PRODUCTIONS = [RUSSIA_PRODUCTION, KOREAN_PRODUCTION, FOREIGN_PRODUCTION]

PRODUCTION_TO_RUS = {
    RUSSIA_PRODUCTION: "российское",
    KOREAN_PRODUCTION: "корейское",
    FOREIGN_PRODUCTION: "зарубежное"
}

QUESTION_MOVIE_BY_BANNER = "banner"
QUESTION_MOVIE_BY_SLOGAN = "slogan"
QUESTION_MOVIE_BY_DESCRIPTION = "description"
QUESTION_MOVIE_BY_SHORT_DESCRIPTION = "short-description"
QUESTION_MOVIE_BY_FACTS = "facts"
QUESTION_MOVIE_BY_AUDIO = "audios"
QUESTION_MOVIE_BY_ACTORS = "actors"
QUESTION_MOVIE_BY_IMAGES = "images"
QUESTION_YEAR_BY_MOVIE = "year"

QUESTIONS = [
    QUESTION_MOVIE_BY_BANNER, QUESTION_MOVIE_BY_SLOGAN, QUESTION_MOVIE_BY_DESCRIPTION, QUESTION_MOVIE_BY_SHORT_DESCRIPTION,
    QUESTION_MOVIE_BY_FACTS, QUESTION_MOVIE_BY_AUDIO, QUESTION_MOVIE_BY_ACTORS, QUESTION_MOVIE_BY_IMAGES, QUESTION_YEAR_BY_MOVIE
]

QUESTION_TO_RUS = {
    QUESTION_MOVIE_BY_BANNER: "кмс по баннеру",
    QUESTION_MOVIE_BY_SLOGAN: "кмс по слогану",
    QUESTION_MOVIE_BY_DESCRIPTION: "кмс по описанию",
    QUESTION_MOVIE_BY_SHORT_DESCRIPTION: "кмс по короткому описанию",
    QUESTION_MOVIE_BY_FACTS: "кмс по фактам",
    QUESTION_MOVIE_BY_AUDIO: "кмс по аудио",
    QUESTION_MOVIE_BY_ACTORS: "кмс по актёрам",
    QUESTION_MOVIE_BY_IMAGES: "кмс по кадрам",
    QUESTION_YEAR_BY_MOVIE: "год по кмс"
}

QUESTION_TO_WEIGHT = {
    QUESTION_MOVIE_BY_BANNER: 4,
    QUESTION_MOVIE_BY_SLOGAN: 5,
    QUESTION_MOVIE_BY_DESCRIPTION: 3,
    QUESTION_MOVIE_BY_SHORT_DESCRIPTION: 3,
    QUESTION_MOVIE_BY_FACTS: 4,
    QUESTION_MOVIE_BY_AUDIO: 5,
    QUESTION_MOVIE_BY_ACTORS: 3,
    QUESTION_MOVIE_BY_IMAGES: 2,
    QUESTION_YEAR_BY_MOVIE: 7
}

QUESTION_YEARS = [1900, 1980, 1990, 2000, 2010, 2015, 2020]


FILM_TYPE = "movie"
CARTOON_TYPE = "cartoon"
SERIES_TYPE = "tv-series"
ANIMATED_SERIES_TYPE = "animated-series"
ANIME_TYPE = "anime"

MOVIE_TYPES = [FILM_TYPE, CARTOON_TYPE, SERIES_TYPE, ANIMATED_SERIES_TYPE, ANIME_TYPE]

MOVIE_TYPE_TO_RUS = {
    FILM_TYPE: "фильм",
    CARTOON_TYPE: "мультфильм",
    SERIES_TYPE: "сериал",
    ANIMATED_SERIES_TYPE: "анимационный сериал",
    ANIME_TYPE: "аниме"
}

MOVIE_TYPE_TO_GENITIVE_RUS = {
    FILM_TYPE: "фильма",
    CARTOON_TYPE: "мультфильма",
    SERIES_TYPE: "сериала",
    ANIMATED_SERIES_TYPE: "анимационного сериала",
    ANIME_TYPE: "аниме"
}

LIST_TOP250_FILMS = "top250"
LIST_TOP500_FILMS = "top500"
LIST_TOP250_SERIES = "series-top250"

TOP_LISTS = [LIST_TOP250_FILMS, LIST_TOP500_FILMS, LIST_TOP250_SERIES]

TOP_LIST_TO_RUS = {
    LIST_TOP250_FILMS: "250 лучших фильмов",
    LIST_TOP500_FILMS: "500 лучших фильмов",
    LIST_TOP250_SERIES: "250 лучших сериалов"
}
